version: '3'
services:
  postgres: 
    image: postgres:10.5
    environment:
      POSTGRES_USER: ${DATABASE_NAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    networks:
      - network
    hostname: postgres
  redis:
    image: 'redis:alpine'
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - network
    hostname: redis
    volumes:
      - ./volumes/redis:/data
  client:
    image: tylerzhang/team-manager-client:latest
    environment:
      API_URL: http://api:8080
    ports:
      - "${PORT}:80"
    hostname: client
    networks:
      - network
  api:
    image: tylerzhang/team-manager-server:latest
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_LOGGING: "false"
      DATABASE_SYNC: "true"
      DATABASE_URL: postgresql://${DATABASE_NAME}@postgres/${DATABASE_NAME}
      REDIS_HOST: redis
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      HOST: ${HOST}
      PRIVATE_KEY: ${API_PRIVATE_KEY}
      SLACK_APP_ID: ${SLACK_APP_ID}
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
    hostname: api
    networks:
      - network
networks:
  network:
    driver: bridge
