version: '3'
services:
  postgres: 
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
